mapping = {
        "BFW":"Bond - FWB",
        "BPF":"Bond - PB",
        "BGB":"Bond - PB",
        "BLB":"Bond - PB",
        "BCT":"Bond - PB",
        "BAP":"Bond - PB",
        "BPP":"Bond - PB",
        "BTN":"Bond - PB",
        "BQC":"Bond - PB",
        "SEL":"Employer's Liab",
        "ECR":"Engineering",
        "EMA":"Engineering",
        "FAHC":"Fire",
        "FIA":"Fire",
        "FFA":"Fire",
        "FPL":"Fire",
        "FAPT":"Fire",
        "FPA":"Fire",
        "FPAI":"Fire",
        "FAR":"Fire",
        "ABA":"Fire",
        "LAA":"Fire",
        "ABU":"Fire",
        "AAR":"Fire",
        "FMI":"Fire",
        "HFW":"FWMI",
        "1BSB":"Maid",
        "2PAQ":"Maid",
        "3GHS":"Maid",
        "7GCV":"Maid",
        "4BCI":"Maid",
        "6GOM":"Maid",
        "5BPB":"Maid",
        "WHPA":"Maid",
        "WHHS":"Maid",
        "WHBD":"Maid",
        "WHM":"Maid",
        "WHMS":"Maid",
        "WHPB":"Maid",
        "8COP":"Maid",
        "1BEM":"Maid",
        "3BWL":"Maid",
        "3CTR":"Maid",
        "3ADH":"Maid",
        "3EHL":"Maid",
        "3DRE":"Maid",
        "3FSG":"Maid",
        "APG":"Misc",
        "AMI":"Misc",
        "AFG":"Misc",
        "MCV":"Motor",
        "MOCV":"Motor",
        "MPC":"Motor",
        "MOPE":"Motor",
        "MALP":"Motor",
        "MPA":"Motor",
        "MPS":"Motor",
        "MSG":"Motor",
        "MBC":"Motor",
        "MFP":"Motor",
        "MPI":"Motor",
        "MZ10":"Motor",
        "MPHS":"Motor",
        "MPT":"Motor",
        "MPN":"Motor",
        "MCT":"Motor",
        "MMC":"Motor",
        "MINL":"Motor",
        "MIEC":"Motor",
        "MIEP":"Motor",
        "MINS":"Motor",
        "MPU":"Motor",
        "MCCF":"Motor fleet",
        "MCVF":"Motor fleet",
        "MPBF":"Motor fleet",
        "MPCF":"Motor fleet",
        "AEI":"Others - Excess",
        "APH":"Others - Excess",
        "APEF":"Others - Excess",
        "AEIP":"Others - Excess",
        "ACV":"Others - Excess",
        "APE":"Others - Excess",
        "ACVF":"Others - Excess",
        "APHF":"Others - Excess",
        "APC":"Others - Warranty",
        "APAG":"PA",
        "PLP":"PA",
        "APPA":"PA",
        "APPJ":"PA",
        "APAI":"PA",
        "APPS":"PA",
        "BSLP":"Package",
        "MT08":"Package",
        "FE01":"Package",
        "FB02":"Package",
        "AM03":"Package",
        "WI04":"Package",
        "LA05":"Package",
        "PA06":"Package",
        "AB07":"Package",
        "MC08":"Package",
        "FE09":"Package",
        "AP10":"Package",
        "BAR":"Package",
        "BBI":"Package",
        "BMI":"Package",
        "BPAG":"Package",
        "BPG":"Package",
        "BFG":"Package",
        "BWIC":"Package",
        "SLL":"PL",
        "CCS":"Trade Credit",
        "WCA":"WIC",
        "WCP":"WIC",
    }